global using System.Globalization;
global using System.Net.Http.Headers;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using Microsoft.Extensions.DependencyInjection;
global using Notion2Ical.Interfaces;
global using Notion2Ical.NotionApi;
global using Notion2Ical.ICalendar;
